# Generated by Django 2.1.5 on 2019-02-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('folder', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
    ]
